syntax = "proto3";

import "google/protobuf/timestamp.proto";

service Account {
  rpc Balance (BalanceRequest) returns (BalanceResponse);
  rpc Statement (StatementExportRequest) returns (stream StatementExport);
}

message BalanceRequest {
    string account_id = 1;
}

message BalanceResponse {
    double balance = 1;
}

message StatementExportRequest {
    string account_id = 1;
    google.protobuf.Timestamp start = 2;
    google.protobuf.Timestamp end = 3;
}

message StatementExport {
    bytes chunk = 1;
    uint64 size = 2;
    uint32 page = 3;
}