<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Confluent.SchemaRegistry.Serdes.Protobuf" Version="2.15.0" />
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
	<PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
	<PackageReference Include="Grpc.Tools" Version="2.83.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
	</PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\proto\movements.proto" Link="Protos\movements.proto" />
  </ItemGroup>

</Project>
